---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
    command: '/lib/systemd/systemd'
    privileged: true
    environment:
      - 'container=docker'
      - 'LC_ALL=C'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu1804
    image: jrei/systemd-ubuntu:18.04
    command: '/lib/systemd/systemd'
    privileged: true
    environment:
      - 'container=docker'
      - 'LC_ALL=C'
      - 'DEBIAN_FRONTEND=noninteractive'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8

# vim:set:ts=2:sw=2:sts=2:et:ft=ansible:
